version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run: echo "Hello World"
      - run: echo $(pwd)
      - run: echo $(ls)