version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run: |
          mkdir layer

      - run: |
          pip install -r requirements.txt -t layer

      - run: |
          chmod +x build_layer.sh
          ./build_layer.sh

      - run: |
          echo $(ls layer)
          echo $(ls layer/bin)