version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run: |
          mkdir -p layer/bin
          mkdir -p layer/python/lib/python3.7/site-packages

      - run: |
          pip install -r requirements.txt -t layer/python/lib/python3.7/site-packages

      - run: |
          chmod +x build_layer.sh
          ./build_layer.sh

      - run: |
          zip -r selenium_layer.zip layer

      - run: |
          echo $(ls)
          echo $(ls layer)
          echo $(ls layer/bin)