version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run: chmod +x build_layer.sh
      - run: ./build_layer.sh
      - run: echo $(ls layer)
      - run: echo $(ls layer/bin)