version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    steps:
      - checkout
      - run: |
          chmod +x build_layer.sh
          ./build_layer.sh
      - run: |
          zip -r selenium_layer.zip layer
      - run: |
          echo $(ls)
          echo $(ls layer)
          echo $(ls layer/bin)
      - run: |
          export AWS_REGION="us-east-1"
      - aws-s3/copy:
          from: selenium_layer.zip
          to: 's3://bcpmax-apartment-artifacts/artifacts/selenium-layer.zip'

  deploy:
    docker:
      - image: hashicorp/terraform:light
    environment:
      BASH_ENV: /root/.bashrc
      TERRAFORM_ENV: ~/project/
    steps:
      - checkout
      - run: |
          echo $(terraform --version)
          terraform init --backend-config="token=${TERRAFORM_TOKEN}"
      - run: |
          terraform plan
      - run: |
          terraform apply -auto-approve

workflows:
  version: 2
  main-workflow:
    jobs:
      - build:
        filters:
            branches:
               only:
                  - master
      - deploy:
         requires:
            - build
         filters:
            branches:
               only:
                  - master
